# Generated by Django 4.0.2 on 2025-03-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tables'),
        ),
    ]
