# Generated by Django 4.0.2 on 2025-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='images/items'),
        ),
    ]
