# Generated by Django 4.0.2 on 2025-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='table',
            field=models.IntegerField(default=0),
        ),
    ]
