# Generated by Django 4.0.2 on 2025-03-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_session_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
