# Generated by Django 4.0.2 on 2025-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ptime',
            field=models.IntegerField(choices=[(1, '1 min'), (5, '5 min'), (10, '10 min'), (15, '15 min')], default=5),
        ),
    ]
