# Generated by Django 4.0.2 on 2025-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField()),
                ('daily', models.IntegerField()),
                ('panels', models.IntegerField()),
                ('items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upass', models.CharField(max_length=50)),
            ],
        ),
    ]
