# Generated by Django 4.0.2 on 2025-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='user',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
