# Generated by Django 4.0.2 on 2025-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_panels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='panels',
            field=models.IntegerField(default=0),
        ),
    ]
