# Generated by Django 4.0.2 on 2025-03-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_metrics_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
