# Generated by Django 5.1.6 on 2025-03-16 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
