# Generated by Django 4.0.2 on 2025-03-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_order_amount_order_date_order_status_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
