# Generated by Django 4.0.2 on 2025-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processing',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queue',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
