# Generated by Django 4.0.2 on 2025-03-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_bill_amount_alter_bill_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
