# Generated by Django 4.0.2 on 2025-03-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_remove_order_session_order_table_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='table_id',
        ),
    ]
