# Generated by Django 4.0.2 on 2025-03-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_order_month_order_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
