# Generated by Django 4.0.2 on 2025-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_alter_order_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('table_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Queue10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('table_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Queue15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('table_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Queue5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('table_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
