# Generated by Django 4.0.2 on 2025-03-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_processing1_processing10_processing15_processing5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
